services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      - APP__ENV=production
      - APP__LIST_LOG_LEVELS=INFO,WARNING,ERROR,CRITICAL
      - VECTOR__STORE_TYPE=weaviate
      - VECTOR__WEAVIATE_HOST=weaviate
      - VECTOR__WEAVIATE_PORT=8080
      - VECTOR__WEAVIATE_GRPC_PORT=50051
    depends_on:
      - weaviate

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.35.9
    ports:
      - 8081:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

volumes:
    weaviate_data:
      driver: local
