[pytest]
addopts = -v --cov=src --cov-report=term-missing --cov-report=html

markers =
    YoutubeTranscriptExtractor: mark tests for YoutubeTranscriptExtractor
    YoutubeExtractor: mark tests for YoutubeExtractor
    YoutubeDataService: mark tests for YoutubeDataService
    std_logger: tests for StdLogger functionality
