[pytest]
addopts = -v --cov=src --cov-report=term-missing --cov-report=html
python_files = test_*.py *_test.py
testpaths = tests

markers =
    YoutubeTranscriptExtractor: mark tests for YoutubeTranscriptExtractor
    YoutubeExtractor: mark tests for YoutubeExtractor
    YoutubeDataService: mark tests for YoutubeDataService
    std_logger: tests for StdLogger functionality
    ChunkRepository: mark tests for chunk repository
    EmbeddingService: mark tests for EmbeddingService
    ModelLoaderService: mark tests for ModelLoaderService
    WeaviateClient: mark tests for WeaviateClient
    WeaviateVector: mark tests for WeaviateVector
    Settings: mark tests for Settings
    YoutubeWeaviateService: mark tests for YoutubeWeaviateService
