"""Add status_message and error_message to content_sources

Revision ID: 04e0f5f5f0af
Revises: 72f69987a221
Create Date: 2026-04-06 14:52:28.300231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04e0f5f5f0af"
down_revision: Union[str, Sequence[str], None] = "72f69987a221"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunk_index", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )
        batch_op.alter_column(
            "content_source_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "job_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=True,
        )

    with op.batch_alter_table("content_sources", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status_message", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("error_message", sa.Text(), nullable=True))
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=True,
        )

    with op.batch_alter_table("diarizations", schema=None) as batch_op:
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.VARCHAR(),
            type_=sa.UUID(),
            existing_nullable=True,
        )
        batch_op.drop_index(batch_op.f("ix_diarizations_title"))
        batch_op.create_index(
            batch_op.f("ix_diarizations_name"), ["name"], unique=False
        )

    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )
        batch_op.alter_column(
            "content_source_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=True,
        )

    with op.batch_alter_table("knowledge_subjects", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge_subjects", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "content_source_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    with op.batch_alter_table("diarizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diarizations_name"))
        batch_op.create_index(
            batch_op.f("ix_diarizations_title"), ["name"], unique=False
        )
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.UUID(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("content_sources", schema=None) as batch_op:
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )
        batch_op.drop_column("error_message")
        batch_op.drop_column("status_message")

    with op.batch_alter_table("chunk_index", schema=None) as batch_op:
        batch_op.alter_column(
            "subject_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "job_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "content_source_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
        )

    # ### end Alembic commands ###
