"""Update unique constraint on content_sources to include subject_id

Revision ID: 0ce7f69147eb
Revises: 5736075a22d0
Create Date: 2026-03-18 12:27:04.170085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ce7f69147eb"
down_revision: Union[str, Sequence[str], None] = "5736075a22d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_content_source_external_source"), "content_sources", type_="unique"
    )
    op.create_unique_constraint(
        "uq_content_source_external_source_per_subject",
        "content_sources",
        ["external_source", "subject_id"],
    )
    op.alter_column(
        "ingestion_jobs",
        "status_message",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ingestion_jobs",
        "status_message",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_constraint(
        "uq_content_source_external_source_per_subject",
        "content_sources",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_content_source_external_source"),
        "content_sources",
        ["external_source"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
