"""add_subject_id_to_ingestion_jobs

Revision ID: 25bc49e441f1
Revises: 946d88fe08b1
Create Date: 2026-03-21 20:12:16.110879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25bc49e441f1"
down_revision: Union[str, Sequence[str], None] = "946d88fe08b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingestion_jobs", sa.Column("subject_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "ingestion_jobs",
        "knowledge_subjects",
        ["subject_id"],
        ["id"],
        initially="IMMEDIATE",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ingestion_jobs", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_column("ingestion_jobs", "subject_id")
    # ### end Alembic commands ###
