"""add status, error_message and model_size to diarizations

Revision ID: 4c007a7c27e8
Revises: f120b614600a
Create Date: 2026-04-03 21:47:53.820978

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c007a7c27e8"
down_revision: Union[str, Sequence[str], None] = "f120b614600a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("diarizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("error_message", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("model_size", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diarizations", schema=None) as batch_op:
        batch_op.drop_column("model_size")
        batch_op.drop_column("error_message")
        batch_op.drop_column("status")
    # ### end Alembic commands ###
