"""add_token_columns_to_content_source

Revision ID: 50420d500c2e
Revises: 4e8d4e04a288
Create Date: 2026-03-20 12:10:12.026548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50420d500c2e"
down_revision: Union[str, Sequence[str], None] = "4e8d4e04a288"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_sources", sa.Column("total_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "content_sources",
        sa.Column("max_tokens_per_chunk", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content_sources", "max_tokens_per_chunk")
    op.drop_column("content_sources", "total_tokens")
    # ### end Alembic commands ###
