"""optimize_sql_models_indexes_and_audit

Revision ID: 5ff7984a3bcc
Revises: e7509b75b129
Create Date: 2026-03-17 01:38:13.879808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ff7984a3bcc"
down_revision: Union[str, Sequence[str], None] = "e7509b75b129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunk_index", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.create_index("ix_chunk_index_chunk_id", ["chunk_id"], unique=False)
        batch_op.create_index(
            "ix_chunk_index_content_source_id", ["content_source_id"], unique=False
        )
        batch_op.create_index(
            op.f("ix_chunk_index_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index("ix_chunk_index_job_id", ["job_id"], unique=False)

    with op.batch_alter_table("content_sources", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.create_index(
            op.f("ix_content_sources_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            op.f("ix_content_sources_processing_status"),
            ["processing_status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_content_sources_source_type", ["source_type"], unique=False
        )
        batch_op.create_index("ix_content_sources_status", ["status"], unique=False)
        batch_op.create_index(
            "ix_content_sources_subject_id", ["subject_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_content_source_external_source", ["external_source"]
        )

    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.create_index(
            "ix_ingestion_jobs_content_source_id", ["content_source_id"], unique=False
        )
        batch_op.create_index(
            op.f("ix_ingestion_jobs_started_at"), ["started_at"], unique=False
        )
        batch_op.create_index("ix_ingestion_jobs_status", ["status"], unique=False)

    with op.batch_alter_table("knowledge_subjects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("knowledge_subjects", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("ingestion_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_ingestion_jobs_status")
        batch_op.drop_index(op.f("ix_ingestion_jobs_started_at"))
        batch_op.create_index(
            "ix_ingestion_jobs_content_source_id", ["content_source_id"], unique=False
        )
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("content_sources", schema=None) as batch_op:
        batch_op.drop_constraint("uq_content_source_external_source", type_="unique")
        batch_op.drop_index("ix_content_sources_subject_id")
        batch_op.drop_index("ix_content_sources_status")
        batch_op.drop_index("ix_content_sources_source_type")
        batch_op.drop_index(op.f("ix_content_sources_processing_status"))
        batch_op.drop_index(op.f("ix_content_sources_created_at"))
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("chunk_index", schema=None) as batch_op:
        batch_op.drop_index("ix_chunk_index_job_id")
        batch_op.drop_index(op.f("ix_chunk_index_created_at"))
        batch_op.drop_index("ix_chunk_index_content_source_id")
        batch_op.drop_index("ix_chunk_index_chunk_id")
        batch_op.drop_column("updated_at")
    # ### end Alembic commands ###
