"""add_subject_id_to_diarization

Revision ID: 6e53bc32edfe
Revises: c48798b08031
Create Date: 2026-04-05 16:20:10.019456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e53bc32edfe"
down_revision: Union[str, Sequence[str], None] = "c48798b08031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diarizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subject_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_diarizations_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_diarization_subject", "knowledge_subjects", ["subject_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diarizations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_diarization_subject", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_diarizations_subject_id"))
        batch_op.drop_column("subject_id")

    # ### end Alembic commands ###
