"""add_metadata_to_chunk_index

Revision ID: 73f13c5ff10a
Revises: 25bc49e441f1
Create Date: 2026-03-21 20:50:50.009318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73f13c5ff10a"
down_revision: Union[str, Sequence[str], None] = "25bc49e441f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    columns = [c["name"] for c in insp.get_columns("chunk_index")]

    with op.batch_alter_table("chunk_index", schema=None) as batch_op:
        if "source_type" not in columns:
            batch_op.add_column(sa.Column("source_type", sa.Text(), nullable=True))
        if "subject_id" not in columns:
            batch_op.add_column(sa.Column("subject_id", sa.UUID(), nullable=True))
        if "external_source" not in columns:
            batch_op.add_column(sa.Column("external_source", sa.Text(), nullable=True))
        if "extra" not in columns:
            batch_op.add_column(sa.Column("extra", sa.JSON(), nullable=True))

        # Check for FK
        fks = insp.get_foreign_keys("chunk_index")
        has_fk = any(
            fk["referred_table"] == "knowledge_subjects"
            and "subject_id" in fk["constrained_columns"]
            for fk in fks
        )
        if not has_fk:
            batch_op.create_foreign_key(
                "fk_chunk_index_subject_id",
                "knowledge_subjects",
                ["subject_id"],
                ["id"],
                initially="IMMEDIATE",
                deferrable=True,
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    columns = [c["name"] for c in insp.get_columns("chunk_index")]

    with op.batch_alter_table("chunk_index", schema=None) as batch_op:
        fks = insp.get_foreign_keys("chunk_index")
        has_fk = any(fk["name"] == "fk_chunk_index_subject_id" for fk in fks)
        if has_fk:
            batch_op.drop_constraint("fk_chunk_index_subject_id", type_="foreignkey")

        if "extra" in columns:
            batch_op.drop_column("extra")
        if "external_source" in columns:
            batch_op.drop_column("external_source")
        if "subject_id" in columns:
            batch_op.drop_column("subject_id")
        if "source_type" in columns:
            batch_op.drop_column("source_type")
    # ### end Alembic commands ###
