"""add_metadata_to_chunk_index

Revision ID: 73f13c5ff10a
Revises: 25bc49e441f1
Create Date: 2026-03-21 20:50:50.009318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73f13c5ff10a"
down_revision: Union[str, Sequence[str], None] = "25bc49e441f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunk_index", sa.Column("source_type", sa.Text(), nullable=True))
    op.add_column("chunk_index", sa.Column("subject_id", sa.UUID(), nullable=True))
    op.add_column("chunk_index", sa.Column("external_source", sa.Text(), nullable=True))
    op.add_column("chunk_index", sa.Column("extra", sa.JSON(), nullable=True))
    op.create_foreign_key(
        None,
        "chunk_index",
        "knowledge_subjects",
        ["subject_id"],
        ["id"],
        initially="IMMEDIATE",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chunk_index", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_column("chunk_index", "extra")
    op.drop_column("chunk_index", "external_source")
    op.drop_column("chunk_index", "subject_id")
    op.drop_column("chunk_index", "source_type")
    # ### end Alembic commands ###
