"""add source_metadata to content_source

Revision ID: 946d88fe08b1
Revises: 50420d500c2e
Create Date: 2026-03-20 21:15:12.128775

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "946d88fe08b1"
down_revision: Union[str, Sequence[str], None] = "50420d500c2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_sources", sa.Column("source_metadata", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content_sources", "source_metadata")
    # ### end Alembic commands ###
