"""created tables

Revision ID: bd01964d9b26
Revises: 
Create Date: 2026-03-12 20:00:31.418076

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd01964d9b26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    current_timestamp = "(CURRENT_TIMESTAMP)"
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(current_timestamp),
                              nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('content_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('external_source', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(current_timestamp),
                              nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('chunks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['knowledge_subjects.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(current_timestamp),
                              nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['knowledge_subjects.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_source_id', sa.UUID(), nullable=True),
                    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text(current_timestamp),
                              nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_source_id'], ['content_sources.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_table('chunk_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_source_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('chars', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(current_timestamp),
                              nullable=False),
    sa.ForeignKeyConstraint(['content_source_id'], ['content_sources.id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_index', if_exists=True)
    op.drop_table('ingestion_jobs', if_exists=True)
    op.drop_table('query_logs', if_exists=True)
    op.drop_table('content_sources', if_exists=True)
    op.drop_table('knowledge_subjects', if_exists=True)
    # ### end Alembic commands ###
