"""Add icon column to KnowledgeSubject

Revision ID: e7509b75b129
Revises: d3b1a2c3d4e5
Create Date: 2026-03-16 20:06:46.989291

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7509b75b129"
down_revision: Union[str, Sequence[str], None] = "d3b1a2c3d4e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge_subjects", sa.Column("icon", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("knowledge_subjects", "icon")

    # ### end Alembic commands ###
