services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    # Start the application automatically
    command: bash -c "uv sync && uv run streamlit run frontend/streamlit_app.py --server.address=0.0.0.0 --server.port=8501"
    environment:
      - APP__ENV=testing
      - APP__LIST_LOG_LEVELS=INFO,WARNING,ERROR,CRITICAL,DEBUG
      - MODEL_EMBEDDING__NAME=BAAI/bge-m3
      - VECTOR__STORE_TYPE=weaviate
      - VECTOR__WEAVIATE_HOST=localhost
      - VECTOR__WEAVIATE_PORT=8081
      - VECTOR__WEAVIATE_API_KEY=
      - VECTOR__WEAVIATE_GRPC_PORT=50051

    network_mode: service:weaviate

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.35.9
    ports:
      - 8081:8080
      - 50051:50051
      - 8501:8501 # Streamlit port mapped through the network host
    volumes:
      - weaviate_dev_data:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

volumes:
  weaviate_dev_data: {}
